### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by emanual4real** [Mekire/meks-pygame-samples#1]
Hey, this is a great example.  Just what I was looking for.  I was having trouble trying to move an object diagonal without speeding it up since the position could only be an int instead of a float.

I'm having a little trouble understanding how you went from pixels per frame to pixels per second.  If you could offer some additional explanation, that would be most appreciated.

Thanks

**Comment by Mekire** [comment]
Glad you found it useful.  Delta time is a little tricky at first.  The return value of `clock.tick()` gives the milliseconds elapsed that frame.  You can convert this to seconds dividing by 1000.  Now instead of defining speeds of objects in how many pixels we want them to move per frame, we instead define them in terms of how many pixels we want them to move per second.

We pass the time delta returned from the `clock.tick` to our update functions and now when moving something we multiply its speed/second by the exact amount of time (in seconds) that elapsed that frame.
Doing this allows us to write frame rate independent games; they will run at the same speed on all machines (theoretically).

In terms of moving objects at speeds that are fractional pixels you need to keep the exact floating position in some proxy variable and set the rect based on this every frame.  I can try to find you some examples of this if you need.

I strongly recommend you read this tutorial on time steps:  
http://gafferongames.com/game-physics/fix-your-timestep/  
It even goes a step further into fixed time steps with interpolation, but that is another story.

Gonna close this as an issue but feel free to respond here.  
Also I moderate https://www.reddit.com/r/pygame/ if you want to ask questions there and https://python-forum.io/ if you have any questions about anything python related or just want to talk with like minded folks..
